export const LOGIN_ACTION = 'AUTH_ACTION/LOGIN_ACTION';
export const START_REQUEST = 'REQUEST_ACTION/START_REQUEST';
export const END_REQUEST = 'REQUEST_ACTION/END_REQUEST';
export const CLEAR_DATA = 'DATA_ACTION/CLEAR_DATA';

export const SET_DATA = 'DATA_ACTION/SET_DATA';
export const CLEAR_SPECIFIC_DATA = 'DATA_ACTION/CLEAR_SPECIFIC_DATA';
export const AUTHENTICATE = 'AUTH_ACTION/AUTHENTICATE';
export const SET_TOKEN = 'AUTH_ACTION/SET_TOKEN';

export const SET_ERROR = 'ERROR_ACTION/SET_ERROR';
export const REMOVE_ERROR = 'ERROR_ACTION/REMOVE_ERROR';
export const RESET_ALL_ERROR = 'ERROR_ACTION/RESET_ALL_ERROR';
