export const LOGIN_ACTION = 'AUTH_ACTION/LOGIN_ACTION';
export const START_REQUEST = 'REQUEST_ACTION/START_REQUEST';
export const END_REQUEST = 'REQUEST_ACTION/END_REQUEST';
export const CLEAR_DATA = 'DATA_ACTION/CLEAR_DATA';

export const SET_DATA = 'DATA_ACTION/SET_DATA';
export const CLEAR_SPECIFIC_DATA = 'DATA_ACTION/CLEAR_SPECIFIC_DATA';
export const AUTHENTICATE = 'AUTH_ACTION/AUTHENTICATE';
