export const LOGIN_ACTION = 'AUTH_ACTION/LOGIN_ACTION';
export const CLEAR_DATA = 'DATA_ACTION/CLEAR_DATA';
export const SET_DATA = 'DATA_ACTION/SET_DATA';
export const CLEAR_SPECIFIC_DATA = 'DATA_ACTION/CLEAR_SPECIFIC_DATA';